name: 'Get repo stats'
description: 'Provides information about issues and pull requests present within the repo'
inputs:
  token: 
    description: 'GITHUB_TOKEN'
    required: true
outputs:
  pulls: 
    description: 'pull requests stats'
  issues:
    description: 'issues stats'
runs:
  using: 'node16'
  main: 'dist/index.js'
