name: "units-test"
on:
  pull_request:
  issues:
  push:

jobs:
  # test action works running from the graph
  repo-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get repo stats
        id: stats
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - name: print repo stats
        run: |
          echo "PRs stats: ${{ steps.stats.outputs.pulls }}"
          echo "Issues stats: ${{ steps.stats.outputs.issues }}"
